ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer: "letsencrypt"
  hosts:
    - host: medcol.io
      paths:
       - "/atlas"
  tls:
    - secretName: medcol-io
      hosts:
       - medcol.io