ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer: "letsencrypt"
  hosts:
    - host: dev.d.medcol.io
      paths:
       - "/atlas"
  tls:
    - secretName: dev-d-medcol-io
      hosts:
       - dev.d.medcol.io