# Default values for atlas-front.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 789776454163.dkr.ecr.us-east-1.amazonaws.com/atlas-front
  tag: latest
  pullPolicy: IfNotPresent

# app specific
# end of app specific

# common container preferences

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5400

ingress:
  enabled: true
  annotations:
    # kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt"
  hosts:
    - host: dev.medcol.io
      paths:
       - "/atlas"
  tls:
    - secretName: dev-medcol-io
      hosts:
       - dev.medcol.io

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}