name: Development Integration

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  check:
    name: Checks
    uses: rerad-io/rerad-devops/.github/workflows/code-quality.yaml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build
    needs: ['check']
    uses: rerad-io/rerad-devops/.github/workflows/docker-image.yaml@main
    with:
      ECR_REPOSITORY: atlas-front
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOT_ENV: |
        VITE_BACKEND_API=${{ secrets.VITE_BACKEND_API }}
        VITE_GA4_MEASUREMENT_ID=${{ secrets.VITE_GA4_MEASUREMENT_ID }}
        VITE_GOOGLE_APP_ID=${{ secrets.VITE_GOOGLE_APP_ID }}
        VITE_ENVIRONMENT=development
        VITE_RELEASE=0.0.1

  deploy:
    name: Deploy
    needs: ['build']
    uses: rerad-io/rerad-devops/.github/workflows/deploy-on-kuber.yaml@main
    with:
      APP: atlas-front
      NAMESPACE: rerad-dev
    secrets:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      args: | 
        -f ./.helm/values.dev.yaml \
        --set image.tag=${{ github.sha }} \
        --wait
