name: PR Preview workflow

env:
  HELM_VERSION: 3.13.2
  NAMESPACE: medcol-dev

on:
  pull_request:
    types: [ 'opened', 'synchronize', 'closed', 'labeled', 'unlabeled' ]
    branches: ['main']

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:

  check:
    name: Checks
    if: github.event.action != 'closed'
    uses: rerad-io/rerad-devops/.github/workflows/code-quality.yaml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build
    needs: ['check']
    uses: rerad-io/rerad-devops/.github/workflows/docker-image.yaml@main
    with:
      ECR_REPOSITORY: atlas-front
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOT_ENV: |
        VITE_BACKEND_API=https://api.d.medcol.io
        VITE_ENVIRONMENT=atlas-front-pr-${{ github.event.number }}
        VITE_RELEASE=0.0.1

  deploy-atlas-front:
    name: Deploy Medcol Front
    needs: ["build"]
    runs-on: dev-runner
    environment: development
    env:
      APP: atlas-front-pr-${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install helm
        uses: Azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}
      - name: Set kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      - name: Upgrade helm release
        env:
          HELM_EXPERIMENTAL_OCI: 1
        run: |
          echo  ${{ secrets.GH_PACKAGE_REPO_PASSWORD }} | helm registry login ghcr.io/${{ github.repository_owner }}/rerad-devops --username ${{ github.repository_owner }} --password-stdin
          helm upgrade ${{ env.APP }} --install oci://ghcr.io/${{ github.repository_owner }}/rerad-devops/universal-front --version 1.1.0 --namespace ${{ env.NAMESPACE }} \
          -f helm-values.yaml \
          -f helm-values.dev.yaml \
          --set image.tag=${{ github.sha }} \
          --set ingress.hosts\[0\].host=atlas-front-pr-${{ github.event.number }}.d.medcol.io \
          --set ingress.hosts\[0\].paths\[0\]=/app \
          --set ingress.tls\[0\].secretName=atlas-front-pr-${{ github.event.number }}-d-medcol-io \
          --set ingress.tls\[0\].hosts\[0\]=atlas-front-pr-${{ github.event.number }}.d.medcol.io \
          --debug \
          --wait

  comment:
    name: Comment
    needs: ['deploy-atlas-front']
    uses: rerad-io/rerad-devops/.github/workflows/deploy-comment.yaml@main
    with:
      APP_HOST: atlas-front-pr-${{ github.event.number }}.d.medcol.io/app
      install: ${{ github.event.action == 'opened' || github.event.action == 'synchronize' }}
  
  uninstall:
    name: Uninstall
    if: github.event.action == 'closed'
    runs-on: dev-runner
    environment: development
    steps:
      - name: install helm
        uses: Azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}
      - name: Set kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      - name: Upgrade helm release
        env:
          HELM_EXPERIMENTAL_OCI: 1
        run: |
          helm uninstall atlas-front-pr-${{ github.event.number }} -n ${{ env.NAMESPACE }}