name: Release Integration

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:

  build:
    name: Build
    uses: rerad-io/rerad-devops/.github/workflows/docker-image.yaml@main
    with:
      runs-on: release-runner
      environment: production
      ECR_REPOSITORY: atlas-front
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOT_ENV: |
        VITE_BACKEND_API=${{ secrets.VITE_BACKEND_API }}
        VITE_GA4_MEASUREMENT_ID=${{ secrets.VITE_GA4_MEASUREMENT_ID }}
        VITE_GOOGLE_APP_ID=${{ secrets.VITE_GOOGLE_APP_ID }}
        VITE_ENVIRONMENT=production
        VITE_RELEASE=0.0.1

  deploy:
    name: Deploy
    needs: ['build']
    uses: rerad-io/rerad-devops/.github/workflows/deploy-on-kuber.yaml@main
    with:
      runs-on: release-runner
      environment: production
      APP: atlas-front
      NAMESPACE: rerad-prod
    secrets:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      args: | 
        -f ./.helm/values.prod.yaml \
        --set image.tag=${{ github.sha }} \
        --wait
